spring:
  application:
    name: blog-server
  config:
    name: ${spring.application.name}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  sleuth:
    sampler:
      probability: 1.0